language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
matrix:
  include:
    - node_js: 11
      script: "node test.js && node test-v10.js"
    - node_js: 10
      script: "node test.js && node test-v10.js"
    - node_js: 8
      script: "node test.js"
    - node_js: 6
      script: "node test.js"
